steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/phoomparin/it-lab-bot', '.']

# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/phoomparin/it-lab-bot']

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['gcloud', 'beta', 'run', 'deploy', '--image', 'gcr.io/phoomparin/it-lab-bot:latest', '--project', 'phoomparin', '--region', 'us-central1', '--memory', '2Gi', '--timeout', '600', '--concurrency', '1', 'it-lab-bot']

images:
- gcr.io/phoomparin/it-lab-bot
